name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ || echo "No tests found"
    
    - name: Build Docker image
      run: |
        docker build -t mobile-pos-backend:${{ github.sha }} .
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker tag mobile-pos-backend:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/mobile-pos-backend:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/mobile-pos-backend:${{ github.sha }}
    
    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        dns-name-label: mobile-pos-backend-${{ github.sha }}
        image: ${{ secrets.ACR_LOGIN_SERVER }}/mobile-pos-backend:${{ github.sha }}
        name: mobile-pos-backend
        location: 'japaneast'
        ports: 8000
        environment-variables: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}
    
    - name: Health check
      run: |
        sleep 30
        curl -f https://mobile-pos-backend-${{ github.sha }}.japaneast.azurecontainer.io/health || exit 1
