name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: app-002-gen10-step3-1-py-oshima8   # ← あなたのApp Service名
  AZURE_WEBAPP_PACKAGE_PATH: pos_tech0_lv1/backend       # ← ここが肝
  PYTHON_VERSION: '3.11'

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive package
        run: zip -r app.zip ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.zip
